# Generated by Django 3.2.9 on 2021-11-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
        ('tablereservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='x',
        ),
    ]
