# Generated by Django 3.2.9 on 2021-11-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablereservation', '0002_rename_reservation_x'),
    ]

    operations = [
        migrations.DeleteModel(
            name='x',
        ),
    ]
