# Generated by Django 3.2.9 on 2021-11-17 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_num',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
